### ISSUE TITLE
Locales related problem

### ISSUE THREAD

**Issue by umed** [jtara1/GetMediaFiles#2]
Hi,

There is problem due reading README.rst during installation:

```
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-v975wf9k/get-media-files/setup.py", line 91, in <module>
        readme = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 312: ordinal not in range(128)
```

There is some solution https://github.com/pytorch/text/issues/77#issuecomment-319206865, but I don't like it.

Can we deal with it somehow else? Maybe try to fix reading README.rst or something else.

Thanks in advance!

**Comment by jtara1** [comment]
for filtering out non ascii chars in python, 

```
>>> def is_ascii(s):
...     return ord(s) < 128
... 
>>> text = open('README.rst', 'r').read()
>>> text2 = ''.join(list(filter(is_ascii, text)))
```
then print text2

script feels like it's not very clean or simple as you'd expect, guess a list comprehension is a little more readable than calling filter

had some special `...` and a certain `'` char in the old readme somehow

made commit & new tag
